---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  - ${DOCKER} test -e /usr/local/bin/duplicity
  - ${DOCKER} test -e /usr/local/sbin/duptools
  - ${DOCKER} duplicity --version
  - ${DOCKER} pip list | grep fasteners
  - ${DOCKER} duptools status | grep 'No backup chains with active signatures found'

  # Check config
  - ${DOCKER} cat /etc/duplicity/duplicity.conf | grep 'export PARAMS'
  - ${DOCKER} cat /etc/duplicity/exclude.list | grep '.cache'

  # Run backup
  - ${DOCKER} duptools backup
  - ${DOCKER} duptools list | grep 'etc/cron.d'
  - ${DOCKER} duptools status | grep 'Found primary backup chain with matching signature chain'

  # Check cronjob
  - ${DOCKER} test -e /etc/cron.d/duplicity
  - ${DOCKER} cat /etc/cron.d/duplicity | grep 'source /etc/duplicity/duplicity.conf'

after_failure:
  - ${DOCKER} duplicity --version
  - ${DOCKER} cat /etc/duplicity/duplicity.conf
  - ${DOCKER} cat /etc/duplicity/exclude.list
  - ${DOCKER} cat /usr/local/sbin/duptools

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
