---
- name: 'Prepare upgrade if versions differ'
  file:
    path: "{{ duplicity_bin }}"
    state: absent
  when: current_duplicity_version != duplicity_version

- name: 'Create duplicity dir'
  file:
    path: "{{ duplicity_workspace }}/duplicity"
    state: directory

- name: 'Download duplicity.tar.gz'
  get_url:
    url: "{{ duplicity_download_url }}"
    dest: "{{ duplicity_workspace }}/{{ duplicity_version }}.tar.gz"

- name: 'Unarchive duplicity.tar.gz'
  unarchive:
    src: "{{ duplicity_workspace }}/{{ duplicity_version }}.tar.gz"
    dest: "{{ duplicity_workspace }}"
    copy: no

- name: 'Install duplicity'
  command: python setup.py install
  args:
    chdir: "{{ duplicity_workspace }}/duplicity-{{ duplicity_version }}"
    creates: "{{ duplicity_bin }}"
