---

- name: 'Prepare upgrade if versions differ'
  file:
    path: "{{ duplicity_bin }}"
    state: absent

- name: 'Create duplicity dir'
  file:
    path: "{{ duplicity_workspace }}/duplicity"
    state: directory

- name: 'Unarchive duplicity.tar.gz'
  unarchive:
    src: "{{ duplicity_download_url }}"
    dest: "{{ duplicity_workspace }}"
    copy: no

- name: 'Install duplicity'
  command: python setup.py install
  args:
    chdir: "{{ duplicity_workspace }}/duplicity-{{ duplicity_version }}"
    creates: "{{ duplicity_bin }}"

- name: 'Remove setup dir'
  file:
    path: "{{ duplicity_workspace }}/duplicity-{{ duplicity_version }}"
    state: absent