---

- name: 'Get current version'
  shell: duplicity --version | cut -f2 -d ' '
  register: current_duplicity_version
  ignore_errors: true
  changed_when: false
  tags: ['always', 'skip_ansible_lint'] #skip ansible lint as shell is required here

- name: Set fact current_duplicity_version
  set_fact:
    current_duplicity_version: '{{ current_duplicity_version.stdout }}'
  tags: ['always']

- name: Show duplicity versions
  debug:
    msg: 'Current: {{ current_duplicity_version }}, Requested: {{ duplicity_version }} '

- name: Install dependencies
  include: install-dependencies.yml
  when: current_duplicity_version != duplicity_version
  tags: ['duplicity-install']

- name: Install duplicity
  include: install.yml
  when: current_duplicity_version != duplicity_version
  tags: ['duplicity-install']

- include: configure.yml
  tags: ['duplicity-configure']
